require 'fileutils'

require 'sprockets'
require 'parcels'

describe "Parcels basic operations", :type => :system do
  context "with a simple widget" do
    before :each do
      files {
        file 'assets/basic.css', %{
          //= require_parcels
        }

        widget 'views/my_widget' do
          css %{
            p { color: red; }
          }
        end
      }
    end

    it "should aggregate the CSS from a simple widget properly" do
      expect_css_content_in('basic',
        'views/my_widget.rb' => {
          widget_scoped(:p) => "color: red"
        })
    end

    it "should apply the correct autogenerated class to the widget contents" do
      content = rendered_widget_content('views/my_widget')
      content.each do |element|
        css_class = element['class']
        puts "ELEMENT: #{element} (#{element.class.name}) -> #{css_class.inspect}"
      end
    end
  end
end
